# Generated by Django 4.0.5 on 2022-08-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_artifact_bestsellinggame_artifact_connectivity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='material',
        ),
    ]
